//! Driving the kernels from the host.
//!
//! [`Ctx`] is the handle to a device: a CubeCL client, the table arena
//! uploaded once, and the [`Fidelity`] measurement that decides which
//! multiply-add the bit-exact kernels are built with. Everything else in this
//! module is generated by the macros at the bottom, one function object per
//! entry in [`crate::function`].
//!
//! ```no_run
//! use cube_math::prelude::*;
//! use cubecl::wgpu::WgpuRuntime;
//!
//! let ctx = Ctx::<WgpuRuntime>::new(&Default::default());
//! let xs: Vec<f64> = (1..=1000).map(|i| i as f64 * 0.001).collect();
//!
//! let exact = Exp::new().eval_f64(&ctx, &xs);            // bit-exact
//! let quick = Exp::fast().eval_f64(&ctx, &xs);           // a few ulp, faster
//! ```
//!
//! # Buffers, not slices
//!
//! The `eval_*` methods take and return `Vec`, which is the convenient thing
//! and also the expensive thing: a round trip to device memory dwarfs the
//! arithmetic for anything under a few hundred thousand elements. The
//! `*_into` methods take device handles instead, and are what you want when
//! the data is already on the device or feeds another kernel.

use core::marker::PhantomData;

use cubecl::prelude::*;
use cubecl::server::Handle;

use crate::config::Config;
use crate::policy::{Accuracy, Domain, Policy};
use crate::probe::Fidelity;

/// A device, its table arena, and what its arithmetic actually does.
///
/// Build one per device and keep it: it owns the uploaded tables, and
/// measuring [`Fidelity`] runs a kernel.
pub struct Ctx<R: Runtime> {
    /// The CubeCL client this context drives.
    pub client: ComputeClient<R>,
    /// What the device does with the operations bit-exactness depends on.
    pub fidelity: Fidelity,
    tables: Handle,
    _r: PhantomData<R>,
}

impl<R: Runtime> Ctx<R> {
    /// Open a context on `device`.
    pub fn new(device: &R::Device) -> Self {
        Self::from_client(R::client(device))
    }

    /// Open a context on an existing client.
    pub fn from_client(client: ComputeClient<R>) -> Self {
        let data = crate::tables::arena::build();
        crate::tables::arena::check(&data);
        let tables = client.create(cubecl::bytes::Bytes::from_elems(data));
        let fidelity = Fidelity::measure(&client);
        let mut ctx = Self { client, fidelity, tables, _r: PhantomData };
        if ctx.fidelity.f64.usable {
            let (exact, approx) = ctx.canary_f64();
            ctx.fidelity.f64.verified = exact;
            // A backend that cannot even get the *approximate* answer right is
            // not a backend with a precision caveat, it is a backend where
            // `f64` does not work.
            ctx.fidelity.f64.usable = approx;
        }
        ctx
    }

    /// Evaluate a real kernel on inputs whose correctly-rounded answers are
    /// mathematical constants, and check them bit for bit.
    ///
    /// The mechanical probes in [`crate::probe`] each test one property, and a
    /// backend can pass all of them and still be wrong. `wgpu`'s WGSL path is
    /// the case in point: it advertises `f64`, has `f64` arithmetic, passes
    /// every probe — and then evaluates `exp(1)` to a number that is not `e`.
    /// So the last word belongs to a whole kernel.
    ///
    /// The expected values are the correctly rounded `f64` nearest to `e^x`,
    /// which is a fact about mathematics rather than about a `libm`, so the
    /// canary does not smuggle in a platform assumption. `exp` is the right
    /// canary because it exercises everything at once: the table read, the
    /// integer exponent surgery, and a chain of eight multiply-adds whose
    /// answer changes if any of them is not fused.
    /// Returns `(bit_exact_ok, approximate_ok)`.
    fn canary_f64(&self) -> (bool, bool) {
        let xs = [1.0f64, -1.0, 0.5, f64::EPSILON, 20.0];
        let want = [
            0x4005_bf0a_8b14_5769u64, // e
            0x3fd7_8b56_362c_ef38,    // 1/e
            0x3ffa_6129_8e1e_069c,    // sqrt(e)
            0x3ff0_0000_0000_0002,    // 1 + 2^-52 + 2^-53, rounded
            0x4176_9b21_ec6e_a4f9,    // e^20
        ];
        let exact = crate::function::Exp::new().eval_f64(self, &xs);
        let fast = crate::function::Exp::fast().eval_f64(self, &xs);
        let ok = |got: &[f64], tol: f64| {
            got.len() == want.len()
                && got.iter().zip(want).all(|(g, w)| {
                    let w = f64::from_bits(w);
                    (g - w).abs() <= tol * w.abs()
                })
        };
        // The approximate arm allows a generous relative error — it is asking
        // "does this backend compute `exp` at all", not "how accurately".
        (ok(&exact, 0.0), ok(&fast, 1e-12))
    }

    /// The compile-time configuration for `policy` in double precision.
    ///
    /// This is where the device's answer meets the caller's: the policy is
    /// whatever was asked for, and the multiply-add is whatever the device can
    /// actually deliver.
    pub fn config_f64(&self, policy: Policy) -> Config {
        Config { policy, fma: self.fidelity.f64.fma_kind() }
    }

    /// The compile-time configuration for `policy` in single precision.
    pub fn config_f32(&self, policy: Policy) -> Config {
        Config { policy, fma: self.fidelity.f32.fma_kind() }
    }

    /// Copy `xs` to the device.
    pub fn upload<E: CubeElement>(&self, xs: &[E]) -> Handle {
        self.client.create(cubecl::bytes::Bytes::from_elems(xs.to_vec()))
    }

    /// Reserve device memory for `n` elements of `E`.
    pub fn alloc<E: CubeElement>(&self, n: usize) -> Handle {
        self.client.empty(n * size_of::<E>())
    }

    /// Read `n` elements of `E` back from the device.
    pub fn download<E: CubeElement + Clone>(&self, h: Handle, n: usize) -> Vec<E> {
        let bytes = self.client.read_one(h).expect("device read failed");
        E::from_bytes(&bytes)[..n].to_vec()
    }

    /// The launch geometry for an `n`-element elementwise kernel.
    ///
    /// One thread per element, in cubes of 256. Elementwise transcendental
    /// work is ALU-bound rather than bandwidth-bound, so there is nothing to
    /// gain from giving each thread several elements, and a flat mapping keeps
    /// the bounds check to one comparison.
    pub fn geometry(&self, n: usize) -> (CubeCount, CubeDim) {
        let dim = 256u32;
        let cubes = n.div_ceil(dim as usize) as u32;
        (CubeCount::Static(cubes.max(1), 1, 1), CubeDim::new_1d(dim))
    }

    /// The table arena, as a launch argument.
    ///
    /// # Safety
    /// The arena is exactly [`crate::tables::arena::ARENA_LEN`] elements long
    /// and every kernel indexes it within the bounds its own offsets declare.
    pub fn tables_arg(&self) -> ArrayArg<R> {
        unsafe {
            ArrayArg::from_raw_parts(
                self.tables.clone(),
                crate::tables::arena::ARENA_LEN,
            )
        }
    }
}

/// A device buffer argument.
///
/// # Safety
/// `n` must not exceed the number of elements the handle was allocated for.
pub unsafe fn arg<R: Runtime>(h: &Handle, n: usize) -> ArrayArg<R> {
    unsafe { ArrayArg::from_raw_parts(h.clone(), n) }
}

/// Common surface of every generated function object.
pub trait MathFn: Copy + Default {
    /// The configured policy.
    fn policy(&self) -> Policy;
    /// The same function with a different policy.
    fn with_policy(self, policy: Policy) -> Self;

    /// Bit-exact, safe on any input. The default.
    fn new() -> Self {
        Self::default()
    }
    /// The cheap approximation, still safe on any input.
    fn fast() -> Self {
        Self::default().with_policy(Policy::FAST)
    }
    /// Take the cheap approximation.
    fn accuracy(self, accuracy: Accuracy) -> Self {
        let mut p = self.policy();
        p.accuracy = accuracy;
        self.with_policy(p)
    }
    /// Promise the inputs are in range.
    fn domain(self, domain: Domain) -> Self {
        let mut p = self.policy();
        p.domain = domain;
        self.with_policy(p)
    }
}
